/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test_project_fleet

class App {
    val greeting: String
        get() {
            val s = "Hello, World!"
            return s
        }
}

fun main() {
    println(App().greeting)
}
