/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package luentokalvo5
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    // println(App().greeting)
    // printOutput()
    // greeting()
    /* rangeDice() 
    The implementation for this file is on the same level as my main application,
    meaning I don't have to import the file before calling the functio.
    */
    firstDice()
    
}

fun printOutput() {
    val a = "Hello, World!"
    println("Output: " + a)
}

fun greeting() {
    val name = "Pekka" // val can not be changed later
    var greeting: String? = null // var can be changed alter
    greeting = "Hello"
    if (greeting != null) {
        println(greeting)
    }
    println(name)
}